### ISSUE TITLE
honk?!?!

### ISSUE THREAD

**Issue by honklol** [Py-Verse/PyBot#3]
honk honkey honk, HONK HONKHONKU??? HONK HONK BONK HONK BONK!!!11!!
<br><br><br><br>
#
#### honk

**Comment by honklol** [comment]
honk honkey honk, cat!

**Comment by honklol** [comment]
honktastic honk honkey honk honk :/

**Comment by AyushSehrawat** [comment]
;-; no spam here

**Comment by honklol** [comment]
HONK?!~?!?!??!!?!?!!? !?! 

>:CCCCCC

**Comment by honklol** [comment]
*`>:CCCCCC`

**Comment by AyushSehrawat** [comment]
Nope
Honk is not defined
